# Use the official Python image
FROM python:3.9-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY src/roommatefinder/requirements /app/requirements
RUN pip install --no-cache-dir -r /app/requirements/dev.txt

# Copy the entire src directory
COPY src /app

# Expose the port
EXPOSE 8000

# Run the application. 
CMD ["python3", "roommatefinder/manage.py", "runserver", "0.0.0.0:8000"]