# Generated by Django 4.1.13 on 2024-04-17 17:53

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='show_me',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dorm_building',
            field=models.CharField(choices=[('1', 'Chapel Glen'), ('2', 'Gateway Heights'), ('3', 'Impact and Prosperity Epicenter'), ('4', 'Kahlert Village'), ('5', 'Lassonde Studios'), ('6', 'Officers Circle'), ('7', 'Sage Point'), ('8', 'Marriott Honors Community'), ('9', 'Guest House'), ('10', 'Off Campus')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='minor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Hanging out with friends'), ('2', 'Shopping'), ('3', 'Road Trips'), ('4', 'Rushing'), ('5', 'Reading'), ('6', 'Concerts'), ('7', 'Staying in'), ('8', 'Going out'), ('9', 'Being outside'), ('10', 'Thrifting'), ('11', 'Photography'), ('12', 'Snowboarding'), ('13', 'Skiing'), ('14', 'Working out'), ('15', 'Anything outdoors'), ('16', 'Hiking'), ('17', 'Surfing'), ('18', 'Music'), ('19', 'Dogs'), ('20', 'Cats'), ('21', 'Fishing'), ('22', 'Hooping'), ('23', 'Cliff Jumping'), ('24', 'Church'), ('25', 'Camping'), ('26', 'Soccer'), ('27', 'Lacrosse'), ('28', 'Dirt Bike'), ('29', 'Chill'), ('30', 'Travel'), ('31', 'Going on runs'), ('32', 'Track and Field'), ('33', 'Football'), ('34', 'Baseball'), ('35', 'Cheer'), ('36', 'Figure Skating'), ('37', 'Cross Country Skiing'), ('38', 'Napping'), ('39', 'Business Scholars'), ('40', 'Honors College'), ('41', 'ROTC'), ('42', 'Rocket League'), ('43', 'Fortnite'), ('44', 'COD'), ('45', 'Drinking'), ('46', 'Smoking'), ('47', 'LGBTQ+'), ('48', 'Mountain Biking'), ('49', 'Rock Climbing'), ('50', 'Nature')], max_length=1000),
        ),
    ]
