# Generated by Django 5.0.7 on 2024-08-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_connection_display_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommatequiz',
            name='bed_time',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='roommatequiz',
            name='clean_room',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='roommatequiz',
            name='guest_policy',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='roommatequiz',
            name='in_room',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='roommatequiz',
            name='sharing_policy',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='roommatequiz',
            name='wake_up_time',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
