# Generated by Django 4.1.13 on 2024-05-13 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='seen_tutorial',
        ),
        migrations.DeleteModel(
            name='Prompt',
        ),
    ]
