# Generated by Django 4.1.13 on 2024-05-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_profile_seen_tutorial_delete_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='key',
            field=models.IntegerField(choices=[('0', 'UNSET'), ('1', 'ONE'), ('2', 'TWO'), ('3', 'THREE'), ('4', 'FOUR')], default='0'),
        ),
    ]
