# Generated by Django 4.1.13 on 2024-05-24 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_photo_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='key',
        ),
    ]
