# Generated by Django 4.1.13 on 2024-05-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_photo_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='key',
            field=models.IntegerField(blank=True, choices=[('0', 'UNSET'), ('1', 'ONE'), ('2', 'TWO'), ('3', 'THREE'), ('4', 'FOUR')], default='0', null=True),
        ),
    ]
