# Generated by Django 4.1.13 on 2024-05-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_photo_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='key',
            field=models.IntegerField(choices=[('0', 'UNSET'), ('1', 'ONE'), ('2', 'TWO'), ('3', 'THREE'), ('4', 'FOUR')], default='0'),
        ),
    ]
