# Generated by Django 4.1.13 on 2024-06-10 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_photo_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommatequiz',
            name='preferred_noise',
        ),
        migrations.AddField(
            model_name='roommatequiz',
            name='bed_time',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='roommatequiz',
            name='clean_room',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='roommatequiz',
            name='guest_policy',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='roommatequiz',
            name='hot_cold',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='roommatequiz',
            name='in_room',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='roommatequiz',
            name='noise_level',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='roommatequiz',
            name='sharing_policy',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='roommatequiz',
            name='social_battery',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='roommatequiz',
            name='wake_up_time',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
