# Generated by Django 4.1.13 on 2024-07-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_profile_instagram_remove_profile_snapchat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dorm_building',
            field=models.CharField(choices=[('1', 'Chapel Glen'), ('2', 'Gateway Heights'), ('3', 'Impact and Prosperity Epicenter'), ('4', 'Kahlert Village'), ('5', 'Lassonde Studios'), ('6', 'Officers Circle'), ('7', 'Sage Point'), ('8', 'Marriott Honors Community'), ('9', 'Guest House'), ('10', "I don't know 🤷\u200d♂️")], max_length=2, null=True),
        ),
    ]
