# Generated by Django 4.1.13 on 2024-07-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_profile_dorm_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='updated',
        ),
        migrations.AddField(
            model_name='connection',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modification date and time'),
        ),
        migrations.AddField(
            model_name='message',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modification date and time'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date and time'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date and time'),
        ),
    ]
