# Generated by Django 4.1.13 on 2024-07-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_profile_max_otp_try_profile_otp_profile_otp_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
