# Generated by Django 4.1.13 on 2024-07-25 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_profile_otp_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='Prompt',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
