name: Test Coverage
on: [pull_request, push]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout action
        uses: actions/checkout@v2
      # install test deps
      - name: Install test deps
        run: pip install -r src/roommatefinder/requirements/test.txt
      # create sample_secrets.json
      - name: Create sample_secrets.json
        run: commands/__tests__/create_secrets.sh
      # run coverage
      - name: Django Coverage action
        run: commands/__tests__/run_coverage_on_api.sh