name: Test Coverage
on: [pull_request, push]
jobs:
  test_project:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout action
        uses: actions/checkout@v2
      - name: Django Coverage action
        run: commands/__tests__/run_tests_on_coverage.sh