name: Test API
on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports: 
          # Maps tcp port 5432 on service container to host
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout action
        uses: actions/checkout@v2
      - name: Setup Python3 action
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.5

      # install test deps
      - name: Install test deps
        run: pip install -r src/roommatefinder/requirements/test.txt
      # create sample_secrets.json
      - name: Create sample_secrets.json
        run: commands/__tests__/create_secrets.sh
        
      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..30}; do
            if pg_isready -h localhost -p 5432 -U postgres; then
              break
            fi
            echo "Waiting for PostgreSQL..."
            sleep 5
          done

      - name: Run migrations
        run: python3 src/roommatefinder/manage.py migrate
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/github_actions

      - name: Run tests
        run: commands/__tests__/run_tests_on_api.sh
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/github_actions