name: Test API
on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        # Docker Hub image
        image: postgres
        env:
          DATABASE_NAME: postgres
          DATABASE_USER: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
        ports: 
          # Maps tcp port 5432 on service container to host
          - 5432

    steps:
      - name: Checkout action
        uses: actions/checkout@v2
      - name: Setup Python3 action
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.5
      # install test deps
      - name: Install test deps
        run: pip install -r src/roommatefinder/requirements/test.txt
      # create sample_secrets.json
      - name: Create sample_secrets.json
        run: commands/__tests__/create_secrets.sh
      # test api
      - name: Run tests
        run: commands/__tests__/run_tests_on_api.sh