name: test_api
on: [pull_request, push]
jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10.5
      - run: pip install -r src/roommatefinder/requirements/test.txt # install test deps
      - run: .github/run_tests_on_api.sh